/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FrameworkRouteImport } from './routes/framework'
import { Route as ScopeRouteImport } from './routes/scope'
import { Route as StartRouteImport } from './routes/start'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as LocalesIndexRouteImport } from './routes/locales/index'
import { Route as LocalesCodeRouteImport } from './routes/locales/$code'
import { Route as PillarsSlugRouteImport } from './routes/pillars/$slug'
import { Route as ProgrammesIndexRouteImport } from './routes/programmes/index'
import { Route as ProgrammesSlugRouteImport } from './routes/programmes/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworkRoute = FrameworkRouteImport.update({
  id: '/framework',
  path: '/framework',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeRoute = ScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalesIndexRoute = LocalesIndexRouteImport.update({
  id: '/locales/',
  path: '/locales/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalesCodeRoute = LocalesCodeRouteImport.update({
  id: '/locales/$code',
  path: '/locales/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarsSlugRoute = PillarsSlugRouteImport.update({
  id: '/pillars/$slug',
  path: '/pillars/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesIndexRoute = ProgrammesIndexRouteImport.update({
  id: '/programmes/',
  path: '/programmes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesSlugRoute = ProgrammesSlugRouteImport.update({
  id: '/programmes/$slug',
  path: '/programmes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/framework': typeof FrameworkRoute
  '/scope': typeof ScopeRoute
  '/start': typeof StartRoute
  '/api/chat': typeof ApiChatRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/locales/$code': typeof LocalesCodeRoute
  '/pillars/$slug': typeof PillarsSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/locales/': typeof LocalesIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/framework': typeof FrameworkRoute
  '/scope': typeof ScopeRoute
  '/start': typeof StartRoute
  '/api/chat': typeof ApiChatRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/locales/$code': typeof LocalesCodeRoute
  '/pillars/$slug': typeof PillarsSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/guides': typeof GuidesIndexRoute
  '/locales': typeof LocalesIndexRoute
  '/programmes': typeof ProgrammesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/framework': typeof FrameworkRoute
  '/scope': typeof ScopeRoute
  '/start': typeof StartRoute
  '/api/chat': typeof ApiChatRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/locales/$code': typeof LocalesCodeRoute
  '/pillars/$slug': typeof PillarsSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/locales/': typeof LocalesIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/framework'
    | '/scope'
    | '/start'
    | '/api/chat'
    | '/guides/$slug'
    | '/locales/$code'
    | '/pillars/$slug'
    | '/programmes/$slug'
    | '/guides/'
    | '/locales/'
    | '/programmes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/framework'
    | '/scope'
    | '/start'
    | '/api/chat'
    | '/guides/$slug'
    | '/locales/$code'
    | '/pillars/$slug'
    | '/programmes/$slug'
    | '/guides'
    | '/locales'
    | '/programmes'
  id:
    | '__root__'
    | '/'
    | '/framework'
    | '/scope'
    | '/start'
    | '/api/chat'
    | '/guides/$slug'
    | '/locales/$code'
    | '/pillars/$slug'
    | '/programmes/$slug'
    | '/guides/'
    | '/locales/'
    | '/programmes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FrameworkRoute: typeof FrameworkRoute
  ScopeRoute: typeof ScopeRoute
  StartRoute: typeof StartRoute
  ApiChatRoute: typeof ApiChatRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  LocalesCodeRoute: typeof LocalesCodeRoute
  PillarsSlugRoute: typeof PillarsSlugRoute
  ProgrammesSlugRoute: typeof ProgrammesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  LocalesIndexRoute: typeof LocalesIndexRoute
  ProgrammesIndexRoute: typeof ProgrammesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/framework': {
      id: '/framework'
      path: '/framework'
      fullPath: '/framework'
      preLoaderRoute: typeof FrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope': {
      id: '/scope'
      path: '/scope'
      fullPath: '/scope'
      preLoaderRoute: typeof ScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locales/': {
      id: '/locales/'
      path: '/locales'
      fullPath: '/locales/'
      preLoaderRoute: typeof LocalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locales/$code': {
      id: '/locales/$code'
      path: '/locales/$code'
      fullPath: '/locales/$code'
      preLoaderRoute: typeof LocalesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillars/$slug': {
      id: '/pillars/$slug'
      path: '/pillars/$slug'
      fullPath: '/pillars/$slug'
      preLoaderRoute: typeof PillarsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/': {
      id: '/programmes/'
      path: '/programmes'
      fullPath: '/programmes/'
      preLoaderRoute: typeof ProgrammesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/$slug': {
      id: '/programmes/$slug'
      path: '/programmes/$slug'
      fullPath: '/programmes/$slug'
      preLoaderRoute: typeof ProgrammesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FrameworkRoute: FrameworkRoute,
  ScopeRoute: ScopeRoute,
  StartRoute: StartRoute,
  ApiChatRoute: ApiChatRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  LocalesCodeRoute: LocalesCodeRoute,
  PillarsSlugRoute: PillarsSlugRoute,
  ProgrammesSlugRoute: ProgrammesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  LocalesIndexRoute: LocalesIndexRoute,
  ProgrammesIndexRoute: ProgrammesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
